name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write 

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}
        with:
          args: |
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.exclusions=**/*.dto.ts,**/*.guard.ts,**/*.spec.ts
            -Dsonar.issue.ignore.multicriteria=e1
            -Dsonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2068
            -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*.spec.ts
          projectBaseDir: .
